FROM node:22-alpine

# Set the working directory
WORKDIR /opt/pluginregistrationapp

# Copy the app to the container
COPY public public/
COPY src src/
COPY package.json .

# Install dependencies
RUN npm install

# PORTS
EXPOSE 3000

# Start the app
CMD [ "npm", "start" ]
