FROM node:22-alpine

# Set the working directory
WORKDIR /opt/pluginregistrationapp

# Environment variables
ARG BACKEND_URL
ENV REACT_APP_BACKEND_URL $BACKEND_URL

# PORTS
EXPOSE 3000

# Copy the app to the container
COPY public public/
COPY src src/
COPY package.json .

# Install dependencies
RUN npm install -g serve
RUN npm install

# Build the app
RUN npm run build

# Start the app
CMD [ "serve", "-s", "build" ]
