services:
  frontend:
    build:
      context: ./client
      dockerfile: dockerfile-dev
      args:
        BACKEND_URL: http://localhost:6969
    develop:
      watch:
        - action: sync
          path: ./client
          target: /opt/pluginregistrationapp/
          ignore:
            - node_modules/
        - action: rebuild
          path: ./client/package.json
    ports:
      - "3000:3000"
    restart: always
  
  backend:
    build:
      context: ./server
      dockerfile: dockerfile
    develop:
      watch:
        - action: rebuild
          path: ./server
    ports:
      - "6969:6969"
    restart: always
    volumes:
      - ./data:/opt/pluginregistrationapp/data
