services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        BACKEND_URL: http://localhost:6969
    develop:
      watch:
        - action: rebuild
          path: ./client
          ignore:
            - node_modules/
    ports:
      - "3000:3000"
    restart: always
  
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    develop:
      watch:
        - action: rebuild
          path: ./server
    ports:
      - "6969:6969"
    restart: always
    volumes:
      - ./data:/opt/pluginregistrationapp/data