services:
  frontend:
    container_name: client
    build:
      dockerfile: ./client-dev.dockerfile
      args:
        BACKEND_URL: http://localhost:6969
    develop:
      watch:
        - action: sync
          path: ./client
          target: /opt/pluginregistrationapp/client
          ignore:
            - node_modules/
        - action: sync
          path: ./models
          target: /opt/pluginregistrationapp/models
        - action: rebuild
          path: ./client-dev.dockerfile
        - action: rebuild
          path: ./client/*.{js,ts,json}
    ports:
      - '5173:5173'
    restart: always

  backend:
    container_name: server
    build:
      dockerfile: ./server-dev.dockerfile
    develop:
      watch:
        - action: sync
          path: ./server
          target: /opt/pluginregistrationapp/server
          ignore:
            - node_modules/
        - action: sync
          path: ./models
          target: /opt/pluginregistrationapp/models
    ports:
      - '6969:6969'
    restart: always
    volumes:
      - ./data:/opt/pluginregistrationapp/data
